name: rtm-env
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - archspec=0.2.5=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.2.0=py312h06d0912_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blosc=1.21.6=hfd34d9b_1
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h477c42c_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - cftime=1.6.4=py312h196c9fc_2
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda=25.11.1=py312h2e8e312_0
  - conda-build=25.11.1=py312h5ae4e53_0
  - conda-index=0.7.0=pyhd8ed1ab_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hf90b1b7_3
  - cpp-expected=1.3.1=h477610d_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - double-conversion=3.4.0=hac47afa_0
  - evalidate=2.0.5=pyhe01879c_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - fmt=12.0.0=h29169d4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - frozendict=2.4.7=py312he06e257_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py312h03cd2ba_101
  - harfbuzz=12.2.0=h5a1b470_1
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_h89f0904_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - ipykernel=6.31.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_2
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.3=h0c9aed9_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblief=0.16.6=hac47afa_1
  - liblzma=5.8.1=h2466b09_2
  - libmamba=2.4.0=h3f46830_1
  - libmambapy=2.4.0=py312h6891394_1
  - libnetcdf=4.9.3=nompi_h7d90bef_103
  - libpng=1.6.53=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.35=h8883371_0
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mbedtls=3.6.3.1=he0c23c2_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.4.2=py312hbb81ca0_0
  - meshio=5.3.5=pyhd8ed1ab_0
  - mkl=2024.2.2=h57928b3_16
  - mpi=1.0=msmpi
  - mpi4py=4.1.1=py312h663871e_102
  - msgpack-python=1.1.2=py312hf90b1b7_1
  - msmpi=10.1.1=h3502643_7
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.3=nompi_py312h79d12a2_100
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - numpy=2.4.0=py312ha72d056_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=10.4.0=py312h381445a_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.0=py312he5662c2_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-lief=0.16.6=py312hbb81ca0_1
  - pyaml=25.7.0=pyhe01879c_0
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py312he06e257_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.10.1=py312h0c8bdd4_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python-libarchive-c=5.3=pyhe01879c_1
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py312h829343e_1
  - pyyaml=6.0.3=py312h05f76fc_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h68b6638_4
  - referencing=0.37.0=pyhcf101f3_0
  - reproc=14.2.5.post0=h2466b09_0
  - reproc-cpp=14.2.5.post0=he0c23c2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - ripgrep=15.1.0=h77a83cd_0
  - rpds-py=0.30.0=py312hdabe01f_0
  - ruamel.yaml=0.18.17=py312he5662c2_2
  - ruamel.yaml.clib=0.2.15=py312he5662c2_1
  - scikit-learn=1.8.0=np2py312hea30aaf_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_1
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=4.2.4=h49e36cd_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - spyder-kernels=3.1.2=win_pyh7428d3b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.7.0=h91493d7_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py312he06e257_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.4=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py312he06e257_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h6a83c73_3
  - yaml-cpp=0.8.0=he0c23c2_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - rtm-rlperdue==0.1
      - scipy==1.16.3
prefix: C:\Users\rperd\miniforge3\envs\rtm-env
